#!/bin/bash

# you can execute this file or walk through the following steps
# to build on linux:

# generage the .pro file
qmake -project -norecursive

# rename the .pro file to the desired executable name
mv src.pro puml.pro

# generage the makefile
qmake

# build the project and run the application in the background
make && ./puml &


# note is not available in any diagram type. needs to
# be available in all types
